frontend:
  image:
    repository: 364478544576.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-repo
    tag: d1fb555cc5677f9a3a056aac64ab6f596ea4ef61

  replicaCount: 1

  service:
    type: ClusterIP
    port: 3000

backend:
  image:
    repository: 364478544576.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-repo
    tag: d1fb555cc5677f9a3a056aac64ab6f596ea4ef61

  replicaCount: 1

  service:
    type: ClusterIP
    port: 5000

database:
  host: dev-employee-db.cl2i66i2usif.ap-south-1.rds.amazonaws.com
  name: employee_db
  port: 5432
  user: postgres
  password: postgres123

autoscaling:
  enabled: false