frontend:
  image:
    repository: 364478544576.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-repo
    tag: frontend-latest

  replicaCount: 1


backend:
  image: 
    repository: 364478544576.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-repo
    tag: backend-latest
    replicaCount: 1


database: 
  host: dev-employee-db.cl2i66i2usif.ap-south-1.rds.amazonaws.com
  name: employee_db 