frontend:
  image:
    repository: 364478544576.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-repo
    tag: frontend-5edeef5d87cb43e18a925db096da9facc960bc9a

  replicaCount: 1

  service:
    type: ClusterIP
    port: 3000

backend:
  image:
    repository: 364478544576.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-repo
    tag: backend-5edeef5d87cb43e18a925db096da9facc960bc9a

  replicaCount: 1

  service:
    type: ClusterIP
    port: 5000

database:
  host: dev-employee-db.cl2i66i2usif.ap-south-1.rds.amazonaws.com
  name: employee_db
  port: 5432

autoscaling:
  enabled: false