grafana:
  enabled: true
  adminUser: admin
  adminPassword: gitops123

  service:
    type: LoadBalancer

prometheus:
  prometheusSpec:
    retention: 7d

alertmanager:
  enabled: true

  alertmanagerSpec:
    useExistingSecret: true
    configSecret: alertmanager-custom-config
