grafana: 
  adminPassword: admin123

  service: 
    type: LoadBalancer

prometheus:
  prometheusSpec:
    storageSpec: null
  service:
    type: LoadBalancer

alertmanager:
  service:
    type: LoadBalancer
    
