apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd

  # annotations:
  #   argocd-image-updater.argoproj.io/image-list: app=364478544576.dkr.ecr.ap-south-1.amazonaws.com/argo-app
  #   argocd-image-updater.argoproj.io/app.kustomize.image-name: 364478544576.dkr.ecr.ap-south-1.amazonaws.com/argo-app
  #   argocd-image-updater.argoproj.io/app.update-strategy: latest
  #   argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
  #   argocd-image-updater.argoproj.io/git-branch: main

spec:
  project: default

  source:
    repoURL: https://github.com/sunilchouhan07/cloud-native-devops-pipeline
    targetRevision: main
    path: gitops-k8s/helm/myapp

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true