name: CD Pipeline 
on:
  workflow_dispatch:

jobs:
  argocd:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::364478544576:role/100DaysOfDevOps
          aws-region: ap-south-1

      - name: Login to EKS Cluster
        run: aws eks update-kubeconfig --region ap-south-1 --name dev-gitops-cluster

      - name: Wait for ArgoCD
        run: |
          kubectl wait --for=condition=available deployment/dev-argocd-server -n argocd --timeout=120s

      - name: Verify ArgoCD
        run: kubectl get pods -n argocd 

      - name: Verify ArgoCD Services
        run: kubectl get svc -n argocd 

      - name: Wait for ArgoCD CRDs 
        run: |
          kubectl wait --for condition=established crd/applications.argoproj.io --timeout=120s

      - name: Deploy app manifest
        working-directory: gitops-k8s/argocd
        run: kubectl apply -f application.yaml

      - name: Verify Applications
        run: kubectl get applications -n argocd






  monitoring-Validation:
    needs: argocd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Helm 
        uses: azure/setup-helm@v4 
      

      - name: Add Helm Repo
        run: |
          helm repo add prometheus-community \
          https://prometheus-community.github.io/helm-charts

          helm repo update 

      - name: Helm Lint 
        run: |
          helm lint  prometheus-community/kube-prometheus-stack \ 
          -f monitoring/values.yaml 
        
      - name: Helm Template Validation
        run: |
          helm template monitoring \
          prometheus-community/kube-prometheus-stack \ 
          -f monitoring/values.yaml > rendered.yaml

      - name: Verify Rendered YAML 
        run: |
          test -s rendered.yaml 
        
      - name: Upload Rendered Manifest 
        uses: actions/upload-artifact@v4
        with: 
          name: rendered
          path: rendered.yaml 
