name: CD Pipeline 
on:
  workflow_dispatch:
  

jobs:
  argocd:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::364478544576:role/100DaysOfDevOps
          aws-region: ap-south-1

      - name: Login to EKS Cluster
        run: aws eks update-kubeconfig --region ap-south-1 --name dev-gitops-cluster

      - name: Wait for ArgoCD
        run: |
          kubectl wait --for=condition=available deployment/dev-argocd-server -n argocd --timeout=120s

      - name: Verify ArgoCD
        run: kubectl get pods -n argocd 

      - name: Verify ArgoCD Services
        run: kubectl get svc -n argocd 

      - name: Wait for ArgoCD CRDs 
        run: |
          kubectl wait --for condition=established crd/applications.argoproj.io --timeout=180s

      - name: Deploy ArgoCD Applications
        working-directory: gitops-k8s/monitoring
        run: |
          kubectl apply -f .

      - name: Deploy ArgoCD Monitoring Applications
        working-directory: gitops-k8s/argocd
        run: |
          kubectl apply -f .

      - name: Verify Applications Health
        run: kubectl get applications -n argocd
