name: CI Pipeline 
on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    env:
      IMAGE_TAG: ${{ github.sha }} 
      BACKEND_REPO: employee-management-backend
      FRONTEND_REPO: employee-management-frontend

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4


      - name: Checkout Employee Management Repo 
        uses: actions/checkout@v4 
        with:
          repository: sunilchouhan07/employee_management_system
          token: ${{ secrets.GH_PAT }}
          path: employee-app 

      - name: Verify Employee Repo
        run: |
          ls -la employee-app
          ls -la employee-app/backend
          ls -la employee-app/frontend


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::364478544576:role/100DaysOfDevOps
          aws-region: ap-south-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name:  Build and Push Backend 
        working-directory: employee-app/backend/
        run: | 
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_REPO }}:$IMAGE_TAG .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_REPO }}:$IMAGE_TAG

      - name:  Build and Push Frontend 
        working-directory: employee-app/frontend/
        run: | 
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_REPO }}:$IMAGE_TAG .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_REPO }}:$IMAGE_TAG

      - name: Helm Lint
        run: helm lint gitops-k8s/helm/myapp

      - name: Helm Template Validation
        run: |
          helm template myapp gitops-k8s/helm/myapp > /dev/null

      - name: Update Helm Image Tag 
        run: |
          sed -i "/frontend:/,/tag:/ s/tag:.*/tag: ${IMAGE_TAG}/" gitops-k8s/helm/myapp/values.yaml
          sed -i "/backend:/,/tag:/ s/tag:.*/tag: ${IMAGE_TAG}/" gitops-k8s/helm/myapp/values.yaml


      - name: Commit Updated Helm Values 
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git add gitops-k8s/helm/myapp/values.yaml 
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes"

      - name: Push Changes 
        run: |
          git push origin main